# Auto-generated by DoScript build — do not edit by hand.
import os, sys, tempfile, shutil, webbrowser

_SCRIPT_NAME = @@SCRIPT_NAME@@
_TITLE       = @@TITLE@@
_BUILD_DATE  = @@BUILD_DATE@@
_DS_VERSION  = @@DS_VERSION@@
_REPO_URL    = @@REPO_URL@@
_DO_SOURCE   = @@DO_SOURCE@@
_RT_SOURCE   = @@RT_SOURCE@@

# ── load the embedded DoScript runtime ────────────────────────────────────────
def _load_runtime():
    import types
    mod = types.ModuleType("_doscript_runtime")
    exec(compile(_RT_SOURCE, "<doscript_runtime>", "exec"), mod.__dict__)
    return mod

_rt = _load_runtime()
DoScriptInterpreter = _rt.DoScriptInterpreter
DoScriptError       = _rt.DoScriptError

# ── UI ────────────────────────────────────────────────────────────────────────
def _banner():
    print("=====================================")
    print(f" {_TITLE}")
    print(f" Powered by DoScript Runtime v{_DS_VERSION}")
    print("=====================================")
    print("Type 'help' for runtime commands.\n")

HELP_TEXT = """\
Runtime commands:
  doscript / about / version  - show runtime info
  link / repo / website       - open official repository
  run                         - run the embedded script again
  restart                     - restart from scratch
  vars                        - show all current variables
  trace on / trace off        - toggle verbose tracing
  exit / quit                 - exit
"""

# ── runtime shell (recovery console on crash, or interactive on request) ──────
def _runtime_shell(interp=None, error=None, script_path=None):
    if error:
        print(f"\n[ERROR] {error.message}")
        if error.line:
            print(f"  line {error.line}: {error.source}")
        print("\nDropping to DoScript Runtime shell. Type 'help' for commands.\n")

    while True:
        try:
            cmd = input("doscript-runtime> ").strip().lower()
        except (EOFError, KeyboardInterrupt):
            print()
            break

        if cmd in ('exit', 'quit'):
            sys.exit(0)
        elif cmd in ('doscript', 'about', 'version'):
            print(f"DoScript Runtime")
            print(f"Version:         {_DS_VERSION}")
            print(f"Embedded Script: {_SCRIPT_NAME}")
            print(f"Build Date:      {_BUILD_DATE}")
            print(f"Official Repo:   {_REPO_URL}")
        elif cmd in ('link', 'repo', 'website', 'docs'):
            print(f"Opening {_REPO_URL} ...")
            webbrowser.open(_REPO_URL)
        elif cmd == 'help':
            print(HELP_TEXT)
        elif cmd in ('run', 'restart'):
            if script_path:
                _run_script(script_path)
            else:
                print("(no script context)")
        elif cmd == 'vars':
            if interp:
                for k, v in sorted(interp.global_vars.items()):
                    if not k.startswith('arg'):
                        print(f"  {k} = {v!r}")
            else:
                print("(no interpreter context)")
        elif cmd == 'trace on':
            if interp:
                interp.verbose = True
            print("Trace enabled.")
        elif cmd == 'trace off':
            if interp:
                interp.verbose = False
            print("Trace disabled.")
        elif cmd == '':
            pass
        else:
            print(f"Unknown command: {cmd!r}. Type 'help'.")

# ── script runner ─────────────────────────────────────────────────────────────
def _run_script(script_path):
    interp = DoScriptInterpreter()
    try:
        interp.run(script_path)
    except DoScriptError as e:
        _runtime_shell(interp=interp, error=e, script_path=script_path)
    except Exception as e:
        print(f"[ERROR] Unexpected: {e}")
        _runtime_shell(script_path=script_path)

# ── entry point ───────────────────────────────────────────────────────────────
def main():
    tmp = tempfile.mkdtemp(prefix="doscript_runtime_")
    script_path = os.path.join(tmp, _SCRIPT_NAME)
    try:
        with open(script_path, 'w', encoding='utf-8') as fh:
            fh.write(_DO_SOURCE)
        _banner()
        _run_script(script_path)
    finally:
        shutil.rmtree(tmp, ignore_errors=True)

if __name__ == '__main__':
    main()
